DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS LOG;

CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD  VARCHAR(255) NOT NULL,
  ROLE VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS GOODS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRICE DOUBLE NOT NULL,
  QUANTITY INTEGER
);

CREATE TABLE IF NOT EXISTS PURCHASINGS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  USER_ID INTEGER NOT NULL,
  GOOD_ID INTEGER NOT NULL,
  PRICE INTEGER,
  QUANTITY INTEGER
);