DROP TABLE IF EXISTS PURCHASINGS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GOODS;

CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(60) NOT NULL,
  PASSWORD  VARCHAR(12) NOT NULL,
  ROLE VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS GOODS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(60),
  PRICE DOUBLE NOT NULL,
  QUANTITY INTEGER
);

CREATE TABLE IF NOT EXISTS PURCHASINGS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  USER_ID INTEGER NOT NULL,
  GOOD_ID INTEGER NOT NULL,
  DATE TIMESTAMP NOT NULL,
  PRICE INTEGER NOT NULL,
  QUANTITY INTEGER
);