DELETE FROM purchasings;
DELETE FROM users;
DELETE FROM goods;

INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Andrey','12345', 'ADMIN');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Zlatan','54321', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Petya','54321', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Masha','54321', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Olya','54321', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Ivanov','54321', 'USER');
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet','Beef', 3.34, 1000);
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet1','Beef5', 2.13, 1000);
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet2','Beef4', 6.87, 1000);
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet3','Beef3', 9.56, 1000);
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet4','Beef2', 15.68, 1000);
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet5','Beef1', 300.54, 1000);
INSERT INTO PURCHASINGS (USER_ID, GOOD_ID, DATE, PRICE, QUANTITY) VALUES (1, 1, '2017-12-12', 3.34, 3);
