DELETE FROM purchasings;
DELETE FROM users;
DELETE FROM goods;

INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Andrey','12345', 'ADMIN');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('Zlatan','54321', 'USER');
INSERT INTO GOODS (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Meet','Beef', 3.34, 10);
INSERT INTO PURCHASINGS (USER_ID, GOOD_ID, DATE, PRICE, QUANTITY) VALUES (1, 1, '2017-12-12', 3.34, 3);
